# Generated by Django 3.2.3 on 2021-06-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Agrupación',
                'verbose_name_plural': 'Agrupaciones',
            },
        ),
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Alcance',
                'verbose_name_plural': 'Alcances',
            },
        ),
        migrations.CreateModel(
            name='AreaACargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Causa',
                'verbose_name_plural': 'Causas',
            },
        ),
        migrations.CreateModel(
            name='ClasificacionImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Clasificación de impacto',
                'verbose_name_plural': 'Clasificaciones de impacto',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Empresa monitoreo',
                'verbose_name_plural': 'Empresas monitoreo',
            },
        ),
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_origen', models.CharField(max_length=50)),
                ('ubicacion_destino', models.CharField(max_length=50)),
                ('caracteristicas', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('cargo', models.CharField(max_length=50, verbose_name='cargo')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=300)),
                ('resumen', models.CharField(max_length=100)),
                ('impacto', models.CharField(max_length=100)),
                ('fecha_conocimiento', models.DateTimeField()),
                ('indisponibilidad', models.BooleanField()),
                ('tiempo_indisponibilidad', models.DateTimeField()),
                ('monitoreo', models.BooleanField()),
                ('fecha_incidente', models.DateTimeField()),
                ('fecha_restauracion', models.DateTimeField()),
                ('ciberseguridad', models.BooleanField()),
                ('causa_principal', models.CharField(max_length=100)),
                ('solucion', models.CharField(max_length=300)),
                ('analisis_posterior', models.CharField(max_length=100)),
                ('control_de_cambios', models.CharField(max_length=200)),
                ('ticket_OTRS', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
                ('agrupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.agrupacion')),
                ('alcance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.alcance')),
                ('area_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.areaacargo')),
                ('clasificacion_impacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.clasificacionimpacto')),
                ('empresas_monitoreo', models.ManyToManyField(to='registro.EmpresaMonitoreo')),
                ('enlace', models.ManyToManyField(to='registro.Enlace')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.estado')),
                ('id_causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.causa')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pais')),
                ('participantes', models.ManyToManyField(to='registro.Participante')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.plataforma')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
            },
        ),
        migrations.CreateModel(
            name='SistemaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Sistema de servicio',
                'verbose_name_plural': 'Sistemas de servicios',
            },
        ),
        migrations.CreateModel(
            name='TipoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Tipo de sistema',
                'verbose_name_plural': 'Tipos de sistema',
            },
        ),
        migrations.CreateModel(
            name='TipoSolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Tipo de solución',
                'verbose_name_plural': 'Tipos de solución',
            },
        ),
        migrations.CreateModel(
            name='UsuariosAfectados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Usuario afectado',
                'verbose_name_plural': 'Usuarios afectados',
            },
        ),
        migrations.CreateModel(
            name='ViaConocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50, verbose_name='nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
            ],
            options={
                'verbose_name': 'Via de conocimiento',
                'verbose_name_plural': 'Vias de conocimiento',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=300)),
                ('plazo', models.DateField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.reporte')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='servidor',
            field=models.ManyToManyField(to='registro.Servidor'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sistema_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.sistemaservicio'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sistemas',
            field=models.ManyToManyField(to='registro.Sistema'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tiposistema'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.tiposolucion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ubicacion',
            field=models.ManyToManyField(to='registro.Ubicacion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuarios_afectados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.usuariosafectados'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='via_conocimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.viaconocimiento'),
        ),
        migrations.CreateModel(
            name='MotivoIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.reporte')),
            ],
            options={
                'verbose_name': 'Motivo incidente',
                'verbose_name_plural': 'Motivos incidentes',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.region'),
        ),
        migrations.CreateModel(
            name='AccionPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.reporte')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.participante')),
            ],
            options={
                'verbose_name': 'Acción preventiva',
                'verbose_name_plural': 'Acciones preventivas',
            },
        ),
        migrations.CreateModel(
            name='AccionIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='editado')),
                ('algo', models.CharField(max_length=50)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.reporte')),
            ],
            options={
                'verbose_name': 'Acción incidente',
                'verbose_name_plural': 'Acciones incidentes',
            },
        ),
    ]
