# Generated by Django 3.2.3 on 2021-07-13 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_region_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comuna',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enlace',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
        migrations.AddField(
            model_name='region',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servidor',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='editado'),
        ),
    ]
