# Generated by Django 3.2.3 on 2021-07-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20210713_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
    ]
