# Generated by Django 3.2.3 on 2021-07-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_pais_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
