# Generated by Django 3.2.3 on 2021-07-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_region_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
