# Generated by Django 3.2.3 on 2021-07-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_rename_id_pais_reporte_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporte',
            old_name='id_causa',
            new_name='causa',
        ),
    ]
